---
script: "./script/cibuild"
gemfile: "this/does/not/exist"
rvm:
      - "2.1.0"
      - "1.9.3"
      - "2.0.0"
      - "2.1.0"
      - "2.1.1"
      - "2.1.2"
before_install:
  - gem update --system 2.1.11 # workaround for https://github.com/rubygems/rubygems/pull/763
